using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ShortLink.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class PartitionLinksByShortCode : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Recreate links table as a hash-partitioned table on ShortCode.
            // This assumes a fresh database or that data can be recreated.
            migrationBuilder.Sql(@"
DO $$
BEGIN
    -- Drop existing non-partitioned table if present
    IF EXISTS (
        SELECT 1
        FROM   pg_catalog.pg_class c
        JOIN   pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE  n.nspname = 'public'
        AND    c.relname = 'links'
        AND    c.relkind = 'r'
    ) THEN
        DROP TABLE public.links CASCADE;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.links (
    ""Id""        bigint GENERATED BY DEFAULT AS IDENTITY,
    ""ShortCode"" character varying(32) NOT NULL,
    ""LongUrl""   character varying(2048) NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_links"" PRIMARY KEY (""Id"")
) PARTITION BY HASH (""ShortCode"");

-- 4 hash partitions for links
CREATE TABLE IF NOT EXISTS public.links_p0 PARTITION OF public.links
    FOR VALUES WITH (MODULUS 4, REMAINDER 0);

CREATE TABLE IF NOT EXISTS public.links_p1 PARTITION OF public.links
    FOR VALUES WITH (MODULUS 4, REMAINDER 1);

CREATE TABLE IF NOT EXISTS public.links_p2 PARTITION OF public.links
    FOR VALUES WITH (MODULUS 4, REMAINDER 2);

CREATE TABLE IF NOT EXISTS public.links_p3 PARTITION OF public.links
    FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE UNIQUE INDEX IF NOT EXISTS ""IX_links_ShortCode"" ON public.links (""ShortCode"");
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS public.links_p0;
DROP TABLE IF EXISTS public.links_p1;
DROP TABLE IF EXISTS public.links_p2;
DROP TABLE IF EXISTS public.links_p3;
DROP TABLE IF EXISTS public.links CASCADE;
");
        }
    }
}
